添加ro1镜像使用说明
cqumirror/mirror-wiki pull request #37
Opened 2023-03-18 13:38 UTC by bro-sin

2023-03-18 13:41 UTC, bro-sin commented
添加ro1镜像使用说明

2023-03-18 19:03 UTC, Hagb requested changes
感谢 PR！这里可能有一些需要更改的地方。

2023-03-18 19:03 UTC, Hagb commented on content/mirror-wiki/ros/_index.md
> +sudo gpg --export -o /etc/apt/trusted.gpg.d/ros1-latest.gpg C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
若以上步骤在非 root 用户下操作，那么 sudo 会导致切换成另一个用户（root），而前面的 gpg 密钥环是用户级别的，切换成另一个用户会导致找不到前面导入的公钥。因此应只对输出部分 sudo：
```suggestion
gpg --export C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 | sudo tee /etc/apt/trusted.gpg.d/ros1-latest.gpg > /dev/null
```

2023-03-19 15:04 UTC, weearc requested changes

2023-03-19 15:04 UTC, weearc commented on content/mirror-wiki/ros/_index.md
> +## 说明
require changechange line line

2023-03-19 15:04 UTC, weearc commented on content/mirror-wiki/ros/_index.md
> +## 适用系统
require change line

2023-03-19 15:04 UTC, weearc commented on content/mirror-wiki/ros/_index.md
> +## 使用说明
require change line

2023-03-19 15:04 UTC, weearc commented on content/mirror-wiki/ros/_index.md
> +### 设置ros1的重大镜像源：
as the document is served from mirror to public , `CQU` is required to remove for being provide itself from CQU mirror

2023-03-20 02:30 UTC, bro-sin commented on content/mirror-wiki/ros/_index.md
> +## 说明
已添加换行

2023-03-20 02:30 UTC, bro-sin commented on content/mirror-wiki/ros/_index.md
> +## 适用系统
已添加换行

2023-03-20 02:54 UTC, bro-sin commented on content/mirror-wiki/ros/_index.md
> +## 使用说明
已添加换行

2023-03-20 02:54 UTC, bro-sin commented on content/mirror-wiki/ros/_index.md
> +### 设置ros1的重大镜像源：
已移除

2023-03-20 05:59 UTC, weearc requested changes
Please remember to add space between Chinese characters and English words.
For example:
```markdown
这是一句中英混合的示例，中间参杂了包括 Linux 的单词。
```

2023-03-20 05:59 UTC, weearc commented on content/mirror-wiki/ros/_index.md
> +rosdep：[清华大学镜像源ROS Distro 帮助](https://mirrors.tuna.tsinghua.edu.cn/help/rosdistro/)
This external link should be link provided by ROS or its community document. No other mirror document should be linked here.

2023-03-20 06:01 UTC, weearc commented
Thank you for providing this document. But some changes should still be made before we merge and generate the whole site

2023-03-20 07:01 UTC, bro-sin commented on content/mirror-wiki/ros/_index.md
> +rosdep：[清华大学镜像源ROS Distro 帮助](https://mirrors.tuna.tsinghua.edu.cn/help/rosdistro/)
添加该链接的原因是因为在 ros1 官方的安装教程里面，有“初始化 rosdep”这个步骤，需要执行下列命令：
```bash
sudo rosdep init
rosdep update
```
但是该步骤在国内的网络环境是无法成功的，目前该问题并没有官方的解决方案。
清华的rosdistro镜像给出了该问题的解决办法。

2023-03-20 07:24 UTC, weearc submitted a review, later dismissed

2023-03-21 09:26 UTC, Hagb submitted a review, later dismissed

2023-03-21 09:40 UTC, weearc approved these changes

2023-03-21 09:43 UTC, merged